force-app/main/default/objects/Task_Manager__c/Task_Manager__c.object-meta.xml
<CustomObject>
    <label>Task Manager</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Manager__c/fields/Task_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Date__c</fullName>
    <label>Task Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/toDoManagerHandlerClass.cls
public with sharing class toDoManagerHandlerClass {
  @AuraEnabled(cacheable=true)
  public static List<Task_Manager__c> getTaskManagerData() {
    try {
      return [
        SELECT Id, Name, Task_Date__c
        FROM Task_Manager__c
        WHERE OwnerId = :UserInfo.getUserId() AND Is_Completed__c = FALSE
        WITH USER_MODE
        ORDER BY Task_Date__c
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Task_Manager__c> getTaskCompletedData() {
    try {
      return [
        SELECT Id, Name, Task_Date__c
        FROM Task_Manager__c
        WHERE OwnerId = :UserInfo.getUserId() AND Is_Completed__c = TRUE
        WITH USER_MODE
        ORDER BY Completed_Date__c DESC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}