force-app/main/default/objects/Cricketer__c/Cricketer__c.object-meta.xml
<CustomObject>
    <label>Cricketer</label>
    <nameField>
        <label>Cricketer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cricketers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cricketer__c/fields/Awards__c.field-meta.xml
<CustomField>
    <fullName>Awards__c</fullName>
    <label>Awards</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Born__c.field-meta.xml
<CustomField>
    <fullName>Born__c</fullName>
    <label>Born</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Date_of_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Joined__c</fullName>
    <label>Date of Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Image_url__c.field-meta.xml
<CustomField>
    <fullName>Image_url__c</fullName>
    <label>Image url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zeland</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>West Indies</fullName>
            </value>
            <value>
                <fullName>Shrilanka</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Zimbabwe</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Runs__c.field-meta.xml
<CustomField>
    <fullName>Runs__c</fullName>
    <label>Runs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Spouse__c.field-meta.xml
<CustomField>
    <fullName>Spouse__c</fullName>
    <label>Spouse</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CricketClassHandler.cls
public with sharing class CricketClassHandler {
  @AuraEnabled(cacheable=true)
  public static List<Cricketer__c> getCricketersInfo(String nationality) {
    try {
      return [
        SELECT
          Id,
          Name,
          Nationality__c,
          Runs__c,
          Image_url__c,
          Born__c,
          Age__c,
          Awards__c,
          Height__c,
          Spouse__c,
          Date_of_Joined__c
        FROM Cricketer__c
        WHERE Nationality__c = :nationality
        WITH USER_MODE
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Cricketer__c> fetchPlayersDetails(String playerId) {
    try {
      return [
        SELECT
          Id,
          Name,
          Nationality__c,
          Runs__c,
          Image_url__c,
          Born__c,
          Age__c,
          Awards__c,
          Height__c,
          Spouse__c,
          Date_of_Joined__c
        FROM Cricketer__c
        WHERE Id = :playerId
        WITH USER_MODE
        LIMIT 1
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}